name: shellcheck

on: [push,pull_request]

jobs:
  shellcheck-sh:
    name: "shellcheck .sh"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "shellcheck .sh"
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"
